# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Tutorial01
                                 A QGIS plugin
 for test 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-11
        copyright            : (C) 2026 by Japan
        email                : ikeda.k.autom92@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Tutorial01 class from file Tutorial01.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tutorial_01 import Tutorial01
    return Tutorial01(iface)
