# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Tutorial01
                                 A QGIS plugin
 for test 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-11
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Japan
        email                : ikeda.k.autom92@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction


from qgis.core import (
    QgsProject,
    QgsVectorLayer,
    QgsFeature,
    QgsGeometry,
    QgsPointXY,
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform
)


# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .tutorial_01_dialog import Tutorial01Dialog
import os.path


class Tutorial01:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Tutorial01_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Tutorial01')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Tutorial01', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/tutorial_01/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u''),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Tutorial01'),
                action)
            self.iface.removeToolBarIcon(action)

    def groud_circle(self):
        # -----------------------
        # パラメータ
        # -----------------------
        lon = 139.7671   # 東京駅 経度
        lat = 35.6812    # 東京駅 緯度
        radius_m = 10000 # 半径（メートル）

        # -----------------------
        # CRS 定義
        # -----------------------
        crs_wgs84 = QgsCoordinateReferenceSystem("EPSG:4326")   # 緯度経度
        crs_meter = QgsCoordinateReferenceSystem("EPSG:3857")  # メートル系（Web Mercator）

        transform_to_meter = QgsCoordinateTransform(
            crs_wgs84,
            crs_meter,
            QgsProject.instance()
        )

        transform_to_wgs84 = QgsCoordinateTransform(
            crs_meter,
            crs_wgs84,
            QgsProject.instance()
        )

        # -----------------------
        # 中心点を作成
        # -----------------------
        center_wgs84 = QgsPointXY(lon, lat)
        center_meter = transform_to_meter.transform(center_wgs84)

        # -----------------------
        # 円（バッファ）作成
        # -----------------------
        circle_geom_meter = QgsGeometry.fromPointXY(center_meter).buffer(
            radius_m,
            64  # 円の滑らかさ（数値↑でより円形）
        )

        # 緯度経度に戻す（表示用）
        circle_geom_wgs84 = QgsGeometry(circle_geom_meter)
        circle_geom_wgs84.transform(transform_to_wgs84)

        # -----------------------
        # メモリレイヤ作成
        # -----------------------
        layer = QgsVectorLayer(
            "Polygon?crs=EPSG:4326",
            "Tokyo_10km_Circle",
            "memory"
        )

        provider = layer.dataProvider()
        feature = QgsFeature()
        feature.setGeometry(circle_geom_wgs84)
        provider.addFeatures([feature])

        layer.updateExtents()
        QgsProject.instance().addMapLayer(layer)

    # def groud_square(self):
    #     # -----------------------
    #     # パラメータ
    #     # -----------------------
    #     lon = 140.1233   # 千葉県庁付近 経度
    #     lat = 35.6046    # 千葉県庁付近 緯度

    #     width_m  = 20000  # 東西幅（メートル）
    #     height_m = 10000  # 南北高さ（メートル）

    #     # -----------------------
    #     # CRS 定義
    #     # -----------------------
    #     crs_wgs84 = QgsCoordinateReferenceSystem("EPSG:4326")
    #     crs_meter = QgsCoordinateReferenceSystem("EPSG:3857")

    #     to_meter = QgsCoordinateTransform(
    #         crs_wgs84,
    #         crs_meter,
    #         QgsProject.instance()
    #     )

    #     to_wgs84 = QgsCoordinateTransform(
    #         crs_meter,
    #         crs_wgs84,
    #         QgsProject.instance()
    #     )

    #     # -----------------------
    #     # 中心点変換
    #     # -----------------------
    #     center_wgs84 = QgsPointXY(lon, lat)
    #     center_meter = to_meter.transform(center_wgs84)

    #     # -----------------------
    #     # 四角形作成（メートル系）
    #     # -----------------------
    #     half_w = width_m / 2
    #     half_h = height_m / 2

    #     rect_meter = QgsRectangle(
    #         center_meter.x() - half_w,
    #         center_meter.y() - half_h,
    #         center_meter.x() + half_w,
    #         center_meter.y() + half_h
    #     )

    #     rect_geom_meter = QgsGeometry.fromRect(rect_meter)

    #     # 緯度経度に戻す
    #     rect_geom_wgs84 = QgsGeometry(rect_geom_meter)
    #     rect_geom_wgs84.transform(to_wgs84)

    #     # -----------------------
    #     # メモリレイヤ作成
    #     # -----------------------
    #     layer = QgsVectorLayer(
    #         "Polygon?crs=EPSG:4326",
    #         "Chiba_Rectangle",
    #         "memory"
    #     )

    #     provider = layer.dataProvider()
    #     feature = QgsFeature()
    #     feature.setGeometry(rect_geom_wgs84)
    #     provider.addFeatures([feature])

    #     layer.updateExtents()
    #     QgsProject.instance().addMapLayer(layer)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False    
            self.dlg = Tutorial01Dialog()

        print("QGIS Plugin develop!!!!!")
        # show the dialog
        self.dlg.show() 
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed

        #### 追加 ################################
        self.dlg.show()
        result = self.dlg.exec_()

        # 円を描画
        self.groud_circle()
        
        # 四角形を描画
        # self.groud_square()
        #### 追加 ################################

        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
